[package]
name = "vpsearch_nocopy"
version = "0.1.0"
authors = ["reynaldo.gil <reynaldo.gil@hooyu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vpsearch = "1.3.5"